### ISSUE TITLE
Slugs need to be mutable

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#259]
For legal reasons, we need to be able to change a slug after publish.

Secondary question: if a slug is changed long after publish, can we store old slugs somewhere and setup redirects in the next.js app?

**Comment by jacqui** [comment]
I started working on this in an effort to get another predefined static page ('thank you') up and running for TNC donations support. It's "easy" to make the slug changeable, but what happens after that requires a bit more thought. Tabling this for now so I can finish the donations work first.

I posted this in slack, but so I don't forget:

I have a doc for the "thank you for the donation" page. I started with: 

* slug: "thank-you"
* preview, publish the content
* loaded the in-progress pages/thank-you.js and saw the doc contents
* changed the slug: "thanks"
* preview, publish
* reload the pages/thank-you.js and still see the old content

This is a special case, of course - the template is hardcoded for a particular slug. For any page, though I think we'd want to, as you suggested in this issue, redirect from the old slug to the new slug instead of displaying an old version of the content.

So to-do: think through how to detect that the slug is changed, as right now whatever slug is specified in the sidebar is used to update the content. Perhaps there's also merit to ensuring only one version of content is allowed to marked as `published: true` for a given google doc ID in each locale?
