### ISSUE TITLE
Published article bodies are empty

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#280]
ruh roh

**Comment by TylerFisher** [comment]
Appears only to happen on initial publish.

**Comment by jacqui** [comment]
Confirmed that this is now fixed in the published version of the add-on; I must have published a version of the add-on that had the article content line of code commented out while I was working on the source tracking. The content blows out the limit on log messaging for scripts which is why I had commented it out temporarily.
