### ISSUE TITLE
How can we handle blockquotes?

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/google-app-scripts#332]
Is it possible to detect an indented block like this?

<img width="639" alt="Screen Shot 2021-09-27 at 3 29 51 PM" src="https://user-images.githubusercontent.com/1077075/134972555-7b195c87-e206-4702-991d-b66b34e8a033.png">

**Comment by jacqui** [comment]
Yes, it's possible to do this.

I was able to update the document processing to result in the following for first a blockquote - an indented paragraph of text - and then a regular non-indented paragraph:

```
{
  "children": [
    {
      "index": 74,
      "style": {},
      "content": "“This should be a block quote,” said the tester."
    }
  ],
  "link": null,
  "type": "blockquote",
  "index": 74,
  "style": "NORMAL_TEXT"
},
{
  "children": [
    {
      "index": 109,
      "style": {},
      "content": "Another regular paragraph of text."
    }
  ],
  "link": null,
  "type": "text",
  "index": 109,
  "style": "NORMAL_TEXT"
}
```

I think it could be enough to label the element as "blockquote" instead of "text" for the purposes of rendering it different, right?

**Comment by TylerFisher** [comment]
Yup, that would work.
